// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjtETtNN5FFCNHpccQdzB-lUPUG8SPJWA',
    appId: '1:651463015534:web:0392824fe7cdb30712fa7f',
    messagingSenderId: '651463015534',
    projectId: 'finora-f4c06',
    authDomain: 'finora-f4c06.firebaseapp.com',
    storageBucket: 'finora-f4c06.firebasestorage.app',
    measurementId: 'G-T82HN0NGKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQriPf2sZOXkF9RTCeQO6C8lDywBqboHM',
    appId: '1:651463015534:android:e6a54ca7be5241d412fa7f',
    messagingSenderId: '651463015534',
    projectId: 'finora-f4c06',
    storageBucket: 'finora-f4c06.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjftNqQ7KwpWVNMVz9lRwBs7VexTGdQv0',
    appId: '1:651463015534:ios:c68f17325f91cc2012fa7f',
    messagingSenderId: '651463015534',
    projectId: 'finora-f4c06',
    storageBucket: 'finora-f4c06.firebasestorage.app',
    iosBundleId: 'com.example.finora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjftNqQ7KwpWVNMVz9lRwBs7VexTGdQv0',
    appId: '1:651463015534:ios:c68f17325f91cc2012fa7f',
    messagingSenderId: '651463015534',
    projectId: 'finora-f4c06',
    storageBucket: 'finora-f4c06.firebasestorage.app',
    iosBundleId: 'com.example.finora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjtETtNN5FFCNHpccQdzB-lUPUG8SPJWA',
    appId: '1:651463015534:web:9f6c10ffc6826c7012fa7f',
    messagingSenderId: '651463015534',
    projectId: 'finora-f4c06',
    authDomain: 'finora-f4c06.firebaseapp.com',
    storageBucket: 'finora-f4c06.firebasestorage.app',
    measurementId: 'G-964EVEXM6Y',
  );
}
